- hosts: all
  gather_facts: true
  tasks:
  - name: Find Users
    ansible.builtin.lineinfile:
      path: /etc/nsswitch.conf
      regexp: '^passwd\:'
      line: 'passwd:         compat sss'
  - name: Find Groups
    ansible.builtin.lineinfile:
      path: /etc/nsswitch.conf
      regexp: '^group\:'
      line: 'group:          compat sss'
  - name: Find Shadow
    ansible.builtin.lineinfile:
      path: /etc/nsswitch.conf
      regexp: '^shadow\:'
      line: 'shadow:         compat sss'
