- hosts: all
  gather_facts: true
  tasks:
  - name: Find Users
    ansible.builtin.lineinfile:
      path: /etc/nsswitch.conf
      regexp: '^passwd\:'
      line: 'passwd:         compat sss'
  - name: Find Groups
    ansible.builtin.lineinfile:
      path: /etc/nsswitch.conf
      regexp: '^group\:'
      line: 'group:          compat sss'
  - name: Find Shadow
    ansible.builtin.lineinfile:
      path: /etc/nsswitch.conf
      regexp: '^shadow\:'
      line: 'shadow:         compat sss'
  - name:  Task 1 - verify web/database processes are not running
    shell: if ps -eaf | egrep 'apache|http|nginx|mysql|postgresql|mariadb'|grep -v grep > /dev/null ;then echo 'process_running';else echo 'process_not_running';fi
    executable: "/bin/bash"
    ignore_errors: true
    register: app_process_check
