- hosts: all
  gather_facts: true
  tasks:
  - name: Provide information about vCenter
    community.vmware.vmware_about_info:
      hostname: 'localhost'
      username: 'admin'
      password: 'password'
    delegate_to: localhost
    register: vcenter_about_info
